### ISSUE TITLE
Interpolated upscalers give error

### ISSUE THREAD

**Issue by grexzen** [DrPleaseRespect/cupscale#4]
**Describe the bug**
Using V3, interpolated models spits out this error.

Error: Can't find upscaled output image! This probably means the AI implementation failed to run correctly.
Index was outside the bounds of the array.
Stack Trace:
at Cupscale.Main.Upscale.GetOutputImg()

Error during FilenamePostprocess(): 
File name cannot be null.
Parameter name: sourceFileName
Stack Trace:
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Cupscale.Main.Upscale.FilenamePostprocess(String file)
The error message was copied to the clipboard.

**To Reproduce**
1. Go to Cuscaple
2. Click on interpolated scaler
3. Choose 2 upscalers (WaifuGAN v3 30000 + 4x Utra Sharp.pth)
4. Click upscale and save
5. See error

**Expected behavior**
Image upscaled and saved

**Session Log (REQUIRED)**
Running in portable mode. Data folder: C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData
Arg: C:\Users\Rex\Downloads\SD\Cupscale New\Cupscale.exe
[GetGpus] Found GPU: NVIDIA GeForce RTX 2070 SUPER
[IOUtils] Copying directory "C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\bin\utils" to "C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\bin\py\utils" (Move: False - RemoveFromName: )
Detected Card: NVIDIA GeForce RTX 2070 SUPER / GPU: TU104-A / Arch: Turing
Initialized Nvidia API. GPU: NVIDIA GeForce RTX 2070 SUPER
[DepCheck] CMD: /C python -V
[DepCheck] System Python Check Output: Python 3.10.6
[DepCheck] Sys Python Ver: Python 3.10.6
Parsing Patrons from CSV...
Found 28 Gold Patrons, 737 Silver Patrons
[Servers] Ping to nmkd-hz.de: 174 ms
[Servers] Ping to nmkd-cb.de: 66 ms
[Servers] Closest Server: USA (St. Louis) (66 ms)
[MainUI] Dropped 1 file(s), first = C:\Users\Rex\Downloads\Tag\pics\Review\01231-3669678584-redshift style, hyper realistic painting portrait of ancient goddess by stjepan sejic, norman rockwell, michael hussar, roberto.png
[ImgProc] Converting C:\Users\Rex\Downloads\Tag\pics\Review\01231-3669678584-redshift style, hyper realistic painting portrait of ancient goddess by stjepan sejic, norman rockwell, michael hussar, roberto.png to PngRaw, DelSrc: False, Fill: True, Ext: UseNew
[ImgProc] Color depth of 01231-3669678584-redshift style, hyper realistic painting portrait of ancient goddess by stjepan sejic, norman rockwell, michael hussar, roberto.png is 24.
[ImgProc] Written image to C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\loaded-img\temp.png
[IOUtils] Copying directory "C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\bin\utils" to "C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\bin\py\utils" (Move: False - RemoveFromName: )
[ImgProc] Preprocessing C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\img-in\01231-3669678584-redshift style, hyper realistic painting portrait of ancient goddess by stjepan sejic, norman rockwell, michael hussar, roberto.png - Fill Alpha: True
[ImgProc] Color depth of 01231-3669678584-redshift style, hyper realistic painting portrait of ancient goddess by stjepan sejic, norman rockwell, michael hussar, roberto.png is 24.
[CMD] /C cd /D "C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\bin\esrgan-pytorch" & "C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\bin\py\python.exe" upscale.py --input "C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\img-in" --output "C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\img-out"   --device_id 0 --fp16  --alpha_mode 0   "C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\models\WaifuGAN_v3_30000.pth;50&C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\models\4x-UltraSharp.pth;50"
[ESRGAN] Failed to parse progress from this line: Model "C" does not exist.
Error: Can't find upscaled output image! This probably means the AI implementation failed to run correctly.

Index was outside the bounds of the array.

Stack Trace:
   at Cupscale.Main.Upscale.GetOutputImg()
FilenamePostprocess: Moving  => -WaifuGAN_v3_30000.50.4x-UltraSharp.50
Error during FilenamePostprocess(): 

File name cannot be null.
Parameter name: sourceFileName

Stack Trace:
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Cupscale.Main.Upscale.FilenamePostprocess(String file)
Overwrite is off - keeping suffix.
[IOUtils] Copying directory "C:\Users\Rex\Downloads\SD\Cupscale New\CupscaleData\img-out" to "C:\Users\Rex\Downloads\Tag\pics\Review" (Move: False - RemoveFromName: )

**Desktop (please complete the following information):**
 - OS Version: W11
 - GPU RTX 2070
 - Implementation Used: ESRGAN PyTorch
 - Model Used: WaifuGAN 30000 + 4x-UltraSharp]

**Comment by DrPleaseRespect** [comment]
Fixed in 9e605ff998e2fb4d9949e9cd485ec2a12e1fc5d8

**Comment by grexzen** [comment]
Thanks!
